# Generated by Django 5.1.2 on 2025-02-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employe_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe_user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
