# Generated by Django 5.1.2 on 2025-02-17 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('performance_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_by', to='employee.employe_user'),
        ),
    ]
