# Generated by Django 5.1.2 on 2025-02-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('performance_management', '0002_alter_performancereview_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='comments',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='reviewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_by', to='employee.employe_user'),
        ),
    ]
