# Generated by Django 5.1.2 on 2025-02-18 06:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_leave_leavequota'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='employee.employe_user'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employe_user'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('SL', 'Sick Leave'), ('CL', 'Casual Leave'), ('PL', 'Paid Leave'), ('LWP', 'Leave Without Pay')], max_length=3),
        ),
        migrations.AlterField(
            model_name='leavequota',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employe_user'),
        ),
        migrations.AlterField(
            model_name='leavequota',
            name='leave_type',
            field=models.CharField(choices=[('SL', 'Sick Leave'), ('CL', 'Casual Leave'), ('PL', 'Paid Leave'), ('LWP', 'Leave Without Pay')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='leavequota',
            unique_together={('employee', 'leave_type')},
        ),
    ]
