# Generated by Django 5.1.2 on 2025-02-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_leave_created_at_alter_leave_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='total_days',
        ),
        migrations.AddField(
            model_name='leave',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
